# Spring properties
spring:
  application:
    name: onlinebookstore  # Identify this application
  freemarker:
    enabled: false     # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false       # Allow Thymeleaf templates to be reloaded at runtime
    #prefix: classpath:/web-server/templates/    # Trailing / mandatory
    # Template location for this application only
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_prodemy_book_store_coba
    username: postgres
    password: shafira009598
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  cloud:
    refresh:
      enabled: false



# Map the error path to error template (for Thymeleaf)
error.path: /error

# HTTP Server
server:
  port: 1212

  